version: '3.8'

services:
  thrive-hub-ssr:
    build:
      context: .
    environment:
      - PORT=8000 
    ports:
      - "8000:8000"
    networks:
      - th_app_shared_network

networks:
  th_app_shared_network:
    external: true
